### ISSUE TITLE
Offline usage can't load tokenizer

### ISSUE THREAD

**Issue by kintong3000** [xhluca/dl-translate#56]
I follow the steps to perform offline operation

At the last step，run inside Python:

```
import dl_translate as dlt

mt = dlt.TranslationModel("cached_model_m2m100", model_family="m2m100")
```

i get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/dl_translate/_translation_model.py", line 126, in __init__
    self._tokenizer = TokenizerFast.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1788, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'cached_model_m2m100'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'cached_model_m2m100' is the correct path to a directory containing all relevant files for a M2M100Tokenizer tokenizer.
```
how to fix it
thanks for your help

**Comment by xhluca** [comment]
It seems `os.rename` creates a symbolic link, not actually move files. `shutil.copytree` is probably better. I updated the readme to use that instead. Let me know if it works.

**Comment by xhluca** [comment]
Awesome. Feel free to reopen if similar issues arise again
